#include <array>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

#include "quadro_controller.hpp"

#include <eigen3/Eigen/Dense>
#include "rclcpp/rclcpp.hpp"
#include "sensor_msgs/msg/joint_state.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"

#include "ament_index_cpp/get_package_share_directory.hpp"

using namespace std::chrono_literals;

// ── Timer periods ────────────────────────────────────────────────
static constexpr auto CONTROL_PERIOD  = 3333us;  // ~300 Hz
static constexpr auto PLANNING_PERIOD = 33ms;     // ~30 Hz
static constexpr auto MPC_PERIOD      = 33ms;     // ~30 Hz
static constexpr double PLANNING_DT   = 0.033;    // seconds, matches PLANNING_PERIOD

// ── Snapshot structs ─────────────────────────────────────────────

struct JointSnapshot {
    std::array<double, quadro::NUM_JOINTS> position{};
    std::array<double, quadro::NUM_JOINTS> velocity{};
    std::array<double, quadro::NUM_JOINTS> effort{};
    bool valid = false;
};

// ── Node ─────────────────────────────────────────────────────────

class QuadroController : public rclcpp::Node {
public:
    QuadroController()
    : Node("quadro_controller")
    {

        std::string package_path = ament_index_cpp::get_package_share_directory("quadruped_control");
        std::string urdf_file = package_path + "/description/isaac_sim/quadro.urdf";        

        try
        {
            controller_ = quadro::Controller(urdf_file, PLANNING_DT);
        }
        catch(const std::exception& e)
        {
            RCLCPP_ERROR(this->get_logger(), "Failed to create controller: %s", e.what());
            throw;
        }
        

        sub_joint_states_ = this->create_subscription<sensor_msgs::msg::JointState>(
            "/joint_states", 10,
            std::bind(&QuadroController::jointStateCallback, this, std::placeholders::_1));

        sub_cmd_vel_ = this->create_subscription<geometry_msgs::msg::Twist>(
            "/cmd_vel", 10,
            std::bind(&QuadroController::cmdVelCallback, this, std::placeholders::_1));


        pub_joint_cmd_ = this->create_publisher<std_msgs::msg::Float64MultiArray>(
            "/forward_effort_controller/commands", 10);


        control_timer_ = this->create_wall_timer(
            CONTROL_PERIOD,
            std::bind(&QuadroController::controlCallback, this));

        mpc_timer_ = this->create_wall_timer(
            MPC_PERIOD,
            std::bind(&QuadroController::mpcCallback, this));

        planning_timer_ = this->create_wall_timer(
            PLANNING_PERIOD,
            std::bind(&QuadroController::planningCallback, this));

        RCLCPP_INFO(this->get_logger(), "Controller started");
    }

private:

    void jointStateCallback(const sensor_msgs::msg::JointState::SharedPtr msg)
    {
        // On first message, build sim↔internal index mapping
        if (!joint_map_ready_) {
            buildJointMap(msg->name);
        }

        std::lock_guard<std::mutex> lock(state_mutex_);
        for (size_t i = 0; i < quadro::NUM_JOINTS; ++i) {
            size_t sim_idx = internal_to_sim_[i];
            if (sim_idx < msg->position.size())
                joint_snap_.position[i] = msg->position[sim_idx];
            if (sim_idx < msg->velocity.size())
                joint_snap_.velocity[i] = msg->velocity[sim_idx];
            if (sim_idx < msg->effort.size())
                joint_snap_.effort[i] = msg->effort[sim_idx];
        }
        joint_snap_.valid = true;

        // Update Pinocchio model right when new data arrives
        Eigen::Map<const Eigen::VectorXd> q(joint_snap_.position.data(), quadro::NUM_JOINTS);
        Eigen::Map<const Eigen::VectorXd> dq(joint_snap_.velocity.data(), quadro::NUM_JOINTS);
        Eigen::Map<const Eigen::VectorXd> effort(joint_snap_.effort.data(), quadro::NUM_JOINTS);
        controller_.updateState(q, dq, effort);
    }

    void cmdVelCallback(const geometry_msgs::msg::Twist::SharedPtr msg)
    {
        // Robot body frame: x=lateral, y=forward — swap from ROS cmd_vel convention
        controller_.setDesiredVelocity(
            Eigen::Vector3d(msg->linear.y, msg->linear.x, msg->linear.z),
            Eigen::Vector3d(msg->angular.x, msg->angular.y, msg->angular.z));
    }

    // How will it destinguish between stance / swing joints - the desired torques should be returned by calculate control, but there,
    // the distinction should be made between torque generated by desired forces on stance legs and torques generated by desired position 
    // by swing/trajectory controller
    void controlCallback()
    {
        {
            std::lock_guard<std::mutex> lock(state_mutex_);
            if (!joint_snap_.valid) return;
        }

        // Returns desired joint positions in canonical (JointIdx) order.
        // publishJointCommand remaps to sim order.
        std::array<double, quadro::NUM_JOINTS> cmd = {};
        if (!controller_.isStandingComplete())
            cmd = controller_.calculateStand(this->get_clock()->now().seconds());
        else
            cmd = controller_.calculateControl();

        publishJointCommand(cmd);
    }

    void mpcCallback()
    {
        // Will contain:
        //   1. Build reference trajectory from cmd_vel
        //   2. Build Ac, Bc dynamics matrices
        //   3. Discretize (ZOH)
        //   4. Form condensed QP (H, g, C)
        //   5. Solve QP
        //   6. Store GRFs for controlCallback
    }

    void planningCallback()
    {
        {
            std::lock_guard<std::mutex> lock(state_mutex_);
            if (!joint_snap_.valid) return;
        }

        controller_.runPlanning();
    }

    // ── Helpers ──────────────────────────────────────────────────

    void buildJointMap(const std::vector<std::string>& sim_names)
    {
        // Build name→sim_index lookup
        std::unordered_map<std::string, size_t> name_to_sim;
        for (size_t i = 0; i < sim_names.size(); ++i) {
            name_to_sim[sim_names[i]] = i;
        }

        // For each internal index, find the corresponding sim index
        bool all_found = true;
        for (size_t i = 0; i < quadro::NUM_JOINTS; ++i) {
            auto it = name_to_sim.find(quadro::EXPECTED_JOINT_NAMES[i]);
            if (it != name_to_sim.end()) {
                internal_to_sim_[i] = it->second;
                if (it->second != i) {
                    RCLCPP_WARN(this->get_logger(),
                        "Joint '%s': sim index %zu != internal index %zu (will remap)",
                        quadro::EXPECTED_JOINT_NAMES[i].c_str(), it->second, i);
                }
            } else {
                RCLCPP_ERROR(this->get_logger(),
                    "Joint '%s' not found in /joint_states!", quadro::EXPECTED_JOINT_NAMES[i].c_str());
                internal_to_sim_[i] = i;  // fallback: identity
                all_found = false;
            }
        }

        sim_joint_names_ = sim_names;
        joint_map_ready_ = true;

        if (all_found) {
            RCLCPP_INFO(this->get_logger(), "Joint map built: all %zu joints matched", quadro::NUM_JOINTS);
        }
    }

    void publishJointCommand(const std::array<double, quadro::NUM_JOINTS>& effort)
    {
        if (!joint_map_ready_) return;

        std_msgs::msg::Float64MultiArray msg;
        msg.data.resize(quadro::NUM_JOINTS, 0.0);

        // Internal canonical order matches controllers.yaml order — direct mapping
        for (size_t i = 0; i < quadro::NUM_JOINTS; ++i) {
            msg.data[i] = effort[i];
        }

        pub_joint_cmd_->publish(msg);
    }

private:
    quadro::Controller controller_;

    // ── State (mutex-protected, written by subscribers) ──────────
    std::mutex state_mutex_;
    JointSnapshot joint_snap_;

    // ── Joint mapping ────────────────────────────────────────────
    bool joint_map_ready_ = false;
    std::array<size_t, quadro::NUM_JOINTS> internal_to_sim_{};  // our index → sim index
    std::vector<std::string> sim_joint_names_;           // original names from sim

    // ── ROS interfaces ───────────────────────────────────────────
    rclcpp::Subscription<sensor_msgs::msg::JointState>::SharedPtr sub_joint_states_;
    rclcpp::Subscription<geometry_msgs::msg::Twist>::SharedPtr sub_cmd_vel_;
    rclcpp::Publisher<std_msgs::msg::Float64MultiArray>::SharedPtr pub_joint_cmd_;
    rclcpp::TimerBase::SharedPtr control_timer_;   // 300 Hz
    rclcpp::TimerBase::SharedPtr mpc_timer_;        // 30 Hz
    rclcpp::TimerBase::SharedPtr planning_timer_;   // 30 Hz
};

int main(int argc, char** argv)
{
    rclcpp::init(argc, argv);
    rclcpp::spin(std::make_shared<QuadroController>());
    rclcpp::shutdown();
    return 0;
}
